project:
  type: website

website:
  title: "Auto Risk Management Tool"
  navbar:
    logo: "images/logo.png"
    left:
      - href: index.qmd
        text: Home
      - href: vehicle-risk.qmd
        text: Vehicle Risk
      - href: driver-risk.qmd
        text: Driver Risk
      - href: references.qmd
        text: References
  sidebar: 
    contents: 
      - href: index.qmd
        text: Home
      - href: vehicle-risk.qmd
        text: Vehicle Risk
      - href: driver-risk.qmd
        text: Driver Risk
      - href: references.qmd
        text: References

format:
  html:
    theme: [lux, custom.scss]
    toc: true



